function raise(num) {
  if(num == 1) {
    log "throw: NotPermittedException"
    throw new NotPermittedException("1")
  } else if(num == 2) {
    log "throw: FileNotFoundException"
    throw new FileNotFoundException("2")
  } else {
    throw new ProcessNotFoundException("other")
  }
}

function func(num) {
  log "func call"
  try {
    log "try"
    raise(num)

  } catch(e: NotPermittedException) {
    assert(e instanceof NotPermittedException)
  } catch(e: FileNotFoundException) {
	assert(e instanceof FileNotFoundException)  
  } catch(e : ProcessNotFoundException) {
	assert(e instanceof ProcessNotFoundException)
  } catch(e : DShellException) {
	assert(false)
  } finally {
    assert(true)
  }
}

func(1)
func(2)
func(3)
